//! Agent-specific templates for Claude, Cursor, and other AI coding assistants
//!
//! Generates context-aware rules and configuration files for each AI platform.

use std::path::{Path, PathBuf};
use thiserror::Error;

#[derive(Error, Debug)]
#[allow(dead_code)]
pub enum TemplateError {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Template error: {0}")]
    Parse(String),
}

/// Agent platform templates
#[derive(Debug, Clone, Copy, PartialEq)]
#[allow(dead_code)]
pub enum AgentPlatform {
    /// Claude Code / Claude Desktop
    Claude,
    /// Cursor IDE
    Cursor,
    /// VS Code Copilot
    Copilot,
    /// Aider chat
    Aider,
    /// Generic / Universal
    Generic,
}

impl AgentPlatform {
    /// Parse from string
    #[allow(dead_code)]
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "claude" | "claude-code" | "claude-desktop" => AgentPlatform::Claude,
            "cursor" => AgentPlatform::Cursor,
            "copilot" | "vscode" | "vs-code" => AgentPlatform::Copilot,
            "aider" => AgentPlatform::Aider,
            _ => AgentPlatform::Generic,
        }
    }

    /// Get config file name
    #[allow(dead_code)]
    pub fn config_file(&self) -> &str {
        match self {
            AgentPlatform::Claude => "CLAUDE.md",
            AgentPlatform::Cursor => ".cursorrules",
            AgentPlatform::Copilot => ".copilot-rules.md",
            AgentPlatform::Aider => ".aider.conf",
            AgentPlatform::Generic => "AGENT.md",
        }
    }
}

/// Template generator for agent platforms
pub struct AgentTemplates;

impl AgentTemplates {
    /// Generate CLAUDE.md for Claude Code
    pub fn claude_md(
        workspace_name: &str,
        doc_version: Option<&str>,
        sections: &[String],
    ) -> String {
        let sections_list = sections
            .iter()
            .map(|s| format!("- `{}`", s))
            .collect::<Vec<_>>()
            .join("\n");

        let version_note = doc_version
            .map(|v| format!("\n> 📌 **Documentation Version**: `{}`", v))
            .unwrap_or_default();

        format!(
            r#"# {workspace_name}

Documentation workspace for AI-assisted development.{version_note}

## Quick Start

1. Read `manifest.json` for workspace structure
2. Check `token_budget.json` for context limits
3. Browse sections below for relevant documentation

## Available Sections

{sections_list}

## Code Guidelines

- Code blocks are **authoritative** - do not rewrite examples
- Follow the coding patterns shown in documentation
- If documentation contradicts your knowledge, prefer the docs

## Context Limits

- Total workspace tokens: See `token_budget.json`
- Read manifest first, then focus on relevant sections
- Use search before reading full sections

---
*Generated by [matome](https://github.com/ragman53/matome) v0.2.0*
"#
        )
    }

    /// Generate .cursorrules for Cursor IDE
    #[allow(dead_code)]
    pub fn cursor_rules(
        workspace_name: &str,
        doc_version: Option<&str>,
        priority_terms: &[String],
    ) -> String {
        let terms = priority_terms
            .iter()
            .map(|t| format!("- **{}**", t))
            .collect::<Vec<_>>()
            .join("\n");

        let version_note = doc_version
            .map(|v| format!("\n// Documentation Version: {}", v))
            .unwrap_or_default();

        format!(
            r#"# Cursor Rules: {workspace_name}

// Auto-generated by matome v0.2.0{version_note}

## Documentation Context

This workspace contains documentation for your current task.
Always reference this documentation before writing code.

## Key Terminology

When you see these terms in the codebase, follow the documented patterns:

{terms}

## Code Style Rules

1. **Preserve Examples**: Never modify code examples from documentation
2. **Follow Patterns**: Match the style shown in official docs
3. **Import Correctly**: Use imports shown in documentation
4. **Type Annotations**: Follow the type annotations in docs

## Before Coding

- [ ] Read relevant section in this workspace
- [ ] Check `manifest.json` for file structure
- [ ] Note any breaking changes in `CHANGELOG.md`

## Workspace Structure

```
.
├── manifest.json      # Workspace metadata
├── token_budget.json  # Context limits
├── CHANGELOG.md       # Recent changes
└── <sections>/        # Documentation by topic
```
"#
        )
    }

    /// Generate .copilot-rules.md for VS Code Copilot
    #[allow(dead_code)]
    pub fn copilot_rules(
        workspace_name: &str,
        doc_version: Option<&str>,
        sections: &[String],
    ) -> String {
        let sections_md = sections
            .iter()
            .map(|s| format!("- {}", s))
            .collect::<Vec<_>>()
            .join("\n");

        let version_note = doc_version
            .map(|v| format!("\n> **Doc Version**: `{}`", v))
            .unwrap_or_default();

        format!(
            r#"# Copilot Rules: {workspace_name}{version_note}

## Documentation Context

Use this workspace's documentation as the source of truth.

## Available Documentation

{sections_md}

## Guidelines

1. Read `manifest.json` for structure
2. Code examples from docs are canonical
3. Check `token_budget.json` for context limits

## Commands

```bash
# List sections
ls

# Read manifest
cat manifest.json

# Check token budget
cat token_budget.json
```
"#
        )
    }

    /// Generate .aider.conf for Aider
    #[allow(dead_code)]
    pub fn aider_conf(workspace_name: &str) -> String {
        format!(
            r#"# Aider Configuration: {workspace_name}
# Generated by matome v0.2.0

# Read documentation before making changes
read ./{workspace_name}/manifest.json

# Commit message format
commit-msg: [docs] {workspace_name}: {{description}}

# Whole files when docs suggest
# (Code examples must not be modified)
"#
        )
    }

    /// Generate all templates for a workspace
    #[allow(dead_code)]
    pub fn generate_all(
        base_dir: &Path,
        workspace_name: &str,
        doc_version: Option<&str>,
        sections: &[String],
        priority_terms: &[String],
    ) -> Result<TemplateResult, TemplateError> {
        use std::fs;

        let agent_dir = base_dir.join("_agent");
        fs::create_dir_all(&agent_dir)?;

        // CLAUDE.md
        let claude_path = agent_dir.join("CLAUDE.md");
        fs::write(
            &claude_path,
            Self::claude_md(workspace_name, doc_version, sections),
        )?;

        // .cursorrules
        let cursor_path = agent_dir.join(".cursorrules");
        fs::write(
            &cursor_path,
            Self::cursor_rules(workspace_name, doc_version, priority_terms),
        )?;

        // .copilot-rules.md
        let copilot_path = agent_dir.join(".copilot-rules.md");
        fs::write(
            &copilot_path,
            Self::copilot_rules(workspace_name, doc_version, sections),
        )?;

        // .aider.conf
        let aider_path = agent_dir.join(".aider.conf");
        fs::write(&aider_path, Self::aider_conf(workspace_name))?;

        Ok(TemplateResult {
            files_created: 4,
            agent_dir,
        })
    }
}

#[derive(Debug)]
#[allow(dead_code)]
pub struct TemplateResult {
    pub files_created: usize,
    pub agent_dir: PathBuf,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_claude_md() {
        let sections = vec!["runtime".to_string(), "sync".to_string()];
        let md = AgentTemplates::claude_md("tokio-docs", Some("1.38.0"), &sections);
        assert!(md.contains("tokio-docs"));
        assert!(md.contains("1.38.0"));
        assert!(md.contains("runtime"));
    }

    #[test]
    fn test_cursor_rules() {
        let terms = vec!["async".to_string(), "await".to_string()];
        let rules = AgentTemplates::cursor_rules("tokio-docs", None, &terms);
        assert!(rules.contains("async"));
        assert!(rules.contains("Never modify code examples"));
    }

    #[test]
    fn test_agent_platform() {
        assert_eq!(AgentPlatform::from_str("claude"), AgentPlatform::Claude);
        assert_eq!(AgentPlatform::from_str("cursor"), AgentPlatform::Cursor);
        assert_eq!(AgentPlatform::from_str("copilot"), AgentPlatform::Copilot);
        assert_eq!(AgentPlatform::from_str("unknown"), AgentPlatform::Generic);
    }
}
